config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spell.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spell/urls.py
from django.urls import path
from . import views

app_name = 'spell'

urlpatterns = [
    path('', views.spell_loby, name='loby'),
    path('room/', views.spell_room, name='room'),
]

spell/models.py
from django.db import models

# Create your models here.

spell/views.py
from django.shortcuts import render
from datetime import datetime

def spell_loby(request):
    mess = ''
    room_id = request.GET.get('c', None)
    if room_id == 'sisu':
        context = {}
        response = render(request, 'spell/spell_loby.html', context)
        tomorrow = datetime.replace(datetime.now(), hour=14, minute=59, second=59)
        expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S UTC")
        response.set_cookie('CID',0,expires=expires)
        return response
    if room_id:
        try:
            now = int(datetime.now().strftime('%H%M%S%f')[:-3])
            temp = '0x'+room_id
            cint = int(temp, 16)
            if 0 < now-cint and now-cint < 10000000:
                context = {'room_id':room_id}
                response = render(request, 'spell/spell_invite.html', context)
                tomorrow = datetime.replace(datetime.now(), hour=14, minute=59, second=59)
                expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S UTC")
                response.set_cookie('CID',0,expires=expires)
                return response
            else:
                mess = '만료된 입장코드입니다.'
        except:
            mess = '올바르지 않은 입장코드입니다.'
    else:
        mess = '추천인만 이용 가능합니다.'
    context = {'mess':mess}
    response = render(request, 'spell/spell_404.html', context)
    tomorrow = datetime.replace(datetime.now(), hour=14, minute=59, second=59)
    expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S UTC")
    response.set_cookie('CID',0,expires=expires)
    return response

def spell_room(request):
    if request.method == 'POST':
        if int(request.COOKIES.get('CID')) == 0:
            #참가
            if request.POST.get('room_id'):
                room_id = request.POST.get('room_id')
                context = {
                    'room_id': room_id,
                }
                response = render(request, 'spell/spell_room.html', context)
                tomorrow = datetime.replace(datetime.now(), hour=14, minute=59, second=59)
                expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S UTC")
                response.set_cookie('CID',1,expires=expires)
                return response
            #생성
            else:
                now = int(datetime.now().strftime('%H%M%S%f')[:-3])
                room_id = hex(now)[2:]
                context = {
                    'room_id': room_id,
                }
                response = render(request, 'spell/spell_room.html', context)
                tomorrow = datetime.replace(datetime.now(), hour=14, minute=59, second=59)
                expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S UTC")
                response.set_cookie('CID',1,expires=expires)
                return response
    context = {'mess':'올바르지 않은 접근'}
    return render(request, 'spell/spell_404.html', context)

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/meta.html" %}
    {% block meta %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/layout/meta.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<meta data-n-head="ssr" property="og:type" content="website">
<meta data-n-head="ssr" property="og:site_name" content="스펠 체크">
<meta data-n-head="ssr" data-hid="url" property="og:url" content="http://www.spell-check.kro.kr/">
<meta data-n-head="ssr" data-hid="title" property="og:title" content="스펠 체크">
<meta data-n-head="ssr" data-hid="description" property="og:description" content="소환사 주문을 확인해보아요.">
<meta data-n-head="ssr" data-hid="image" property="og:image" content="{% static 'images/og.png'%}">
<script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

templates/spell/spell_404.html
{% extends 'layout/base.html' %}
{% load static %}

{% block meta %}
<script src="{% static 'js/spell_404.js' %}"></script>
{% endblock %}

{% block title %}
404
{% endblock %}

{% block content %}
{{mess}}
{% endblock %}

templates/spell/spell_invite.html
{% extends 'layout/base.html' %}
{% load static %}

{% block meta %}
<script src="{% static 'js/spell_invite.js' %}?{% now 'U' %}"></script>
{% endblock %}

{% block title %}
spell_invite
{% endblock %}

{% block content %}
대충 설명
<form id="loby_form" class="input-group mt-3" method="post" action="{% url 'spell:room' %}">
    {% csrf_token %}
    <input type="hidden" id="room_id" name="room_id" value="{{room_id}}">
</form>
<button type="button" onClick="submit();">참가</button>
{% endblock %}

templates/spell/spell_loby.html
{% extends 'layout/base.html' %}
{% load static %}

{% block meta %}
<script src="{% static 'js/spell_loby.js' %}?{% now 'U' %}"></script>
{% endblock %}

{% block title %}
spell_loby
{% endblock %}

{% block content %}
<form id="loby_form" class="input-group mt-3" method="post" action="{% url 'spell:room' %}">
    {% csrf_token %}
    <input type="hidden" id="room_id" name="room_id" value="{{room_id}}">
</form>
<button onClick="submit();">create</button>
{% endblock %}

templates/spell/spell_room.html
{% extends 'layout/base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/spell.css' %}">
{{ room_id|json_script:"id" }}
<script>
    const room_id = JSON.parse(document.getElementById('id').textContent);
    const url = "{% if request.is_secure %}https{% else %}http{% endif %}://{{ request.get_host }}{% url 'spell:loby' %}?c="+room_id;
</script>
<script type="text/babel" src="{% static 'js/spell_room.js' %}?{% now 'U' %}"></script>
{% endblock %}

{% block title %}
spell_room
{% endblock %}

{% block content %}
{{room_id}}
<main id="root">
</main>
{% endblock %}